//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int id { get; set; }
        public int questionaryId { get; set; }
        public int questionId { get; set; }
        public Nullable<int> answerListItemId { get; set; }
        public string text { get; set; }
        public int clientId { get; set; }
    
        public virtual AnswerListItem AnswerListItem { get; set; }
        public virtual Client Client { get; set; }
        public virtual Question Question { get; set; }
    }
}
