//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Answers = new HashSet<Answer>();
            this.Documents = new HashSet<Document>();
        }
    
        public int id { get; set; }
        public System.DateTime createdOn { get; set; }
        public int createdBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public int modifiedBy { get; set; }
        public byte typeId { get; set; }
        public short timeZoneId { get; set; }
        public short countryId { get; set; }
        public string city { get; set; }
        public byte height { get; set; }
        public byte weight { get; set; }
        public byte artPresSystolic { get; set; }
        public byte artPresDiastolic { get; set; }
        public string bloodGroup { get; set; }
        public string rhFactor { get; set; }
        public System.TimeSpan wakeUpTime { get; set; }
        public System.TimeSpan sleepTime { get; set; }
        public byte employmentTypeId { get; set; }
        public Nullable<System.TimeSpan> employmentFrom { get; set; }
        public Nullable<System.TimeSpan> employmentTill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual Country Country { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
