//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int id { get; set; }
        public System.DateTime createdOn { get; set; }
        public int createdBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public int modifiedBy { get; set; }
        public byte typeId { get; set; }
    
        public virtual CoachType CoachType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
