//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public System.Guid messageId { get; set; }
        public short typeId { get; set; }
        public byte[] data { get; set; }
        public byte[] dataCompressed { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual Message Message { get; set; }
    }
}
