//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public string application { get; set; }
        public System.DateTime logged { get; set; }
        public string level { get; set; }
        public string message { get; set; }
        public string userName { get; set; }
        public string serverName { get; set; }
        public string port { get; set; }
        public string url { get; set; }
        public Nullable<bool> https { get; set; }
        public string serverAddress { get; set; }
        public string remoteAddress { get; set; }
        public string logger { get; set; }
        public string callsite { get; set; }
        public string exception { get; set; }
    }
}
