//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid id { get; set; }
        public int groupUserId { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public short typeId { get; set; }
        public Nullable<byte> approvalStateId { get; set; }
        public Nullable<System.DateTime> approvalStateOn { get; set; }
        public Nullable<int> approvalStateById { get; set; }
        public string text { get; set; }
    
        public virtual ApprovalState ApprovalState { get; set; }
        public virtual Content Content { get; set; }
        public virtual GroupUser GroupUser { get; set; }
        public virtual GroupUser GroupUser1 { get; set; }
        public virtual MessageType MessageType { get; set; }
    }
}
