//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TEMP_groups
    {
        public int groupId { get; set; }
        public string groupName { get; set; }
        public Nullable<int> participantId { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<int> userId { get; set; }
        public string firstName { get; set; }
        public string cellphone { get; set; }
    }
}
