//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSignalR_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User
    {
        public int id { get; set; }
        public System.DateTime createdOn { get; set; }
        public int createdBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public int modifiedBy { get; set; }
        public string cellphone { get; set; }
        public byte genderId { get; set; }
        public string firstName { get; set; }
        public string fatherName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthday { get; set; }
        public string email { get; set; }
        public string skype { get; set; }
        public bool isOnline { get; set; }
    }
}
